"""Trains a probe (logistic regression baseline, compared against a Random
Forest and a small MLP) to predict a question's category from its task
heuristic and real-activation feature vector.

Run as: `.venv/bin/python -m app.probes.train` from `backend/`.

This performs real forward passes through the local Qwen2.5-1.5B model over
every item in `data/benchmark.json` (a few minutes on CPU/MPS for ~50
items) -- there is no shortcut/mock path here, because the entire point is
training on genuine activation statistics. Writes:
  - `app/probes/saved/probe_pipeline.joblib` (the fitted best model)
  - `app/probes/saved/probe_meta.json` (accuracy, categories, feature names)
  - `docs/PROBE_RESULTS.md` (human-readable eval report, real numbers only)
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from app.activations.features import summarize
from app.cognitive_state.task_analyzer import analyze_task
from app.llm.local_hf_provider import LocalHFProvider
from app.probes.feature_builder import FEATURE_NAMES, build_feature_vector

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_PROJECT_ROOT = _BACKEND_DIR.parent
_DATA_PATH = _PROJECT_ROOT / "data" / "benchmark.json"
_SAVED_DIR = Path(__file__).parent / "saved"
_DOCS_PATH = _PROJECT_ROOT / "docs" / "PROBE_RESULTS.md"


def _load_dataset() -> list[dict]:
    data = json.loads(_DATA_PATH.read_text())
    return data["items"]


def _build_dataset() -> tuple[list[list[float]], list[str], list[str]]:
    items = _load_dataset()
    provider = LocalHFProvider()
    extractor = provider.get_activation_extractor()

    features: list[list[float]] = []
    labels: list[str] = []
    ids: list[str] = []
    for item in items:
        query = item["query"]
        task = analyze_task(query)
        _answer, capture = extractor.capture(query, max_new_tokens=60)
        summary = summarize(capture)
        features.append(build_feature_vector(task, summary))
        labels.append(item["category"])
        ids.append(item["id"])
        print(f"captured {item['id']} ({item['category']})")

    return features, labels, ids


def _write_report(results: dict, best_name: str, categories: list[str], cm, n_test: int) -> None:
    lines = [
        "# Probe results",
        "",
        "Generated by `backend/app/probes/train.py` against `data/benchmark.json`. "
        "These are real train/test-split evaluation numbers from an actual run of the "
        "local model -- not hardcoded or estimated.",
        "",
        "## Model comparison (held-out test accuracy)",
        "",
    ]
    for name, r in results.items():
        marker = "  <- selected" if name == best_name else ""
        lines.append(f"- `{name}`: {r['accuracy']:.3f}{marker}")

    lines += ["", f"## Confusion matrix (`{best_name}`, rows = true category, cols = predicted)", "", "```"]
    header = " " * 10 + " ".join(f"{c[:9]:>9}" for c in categories)
    lines.append(header)
    for cat, row in zip(categories, cm):
        lines.append(f"{cat[:9]:>9} " + " ".join(f"{v:>9}" for v in row))
    lines += ["```", "", f"Test set size: {n_test}"]
    lines += [
        "",
        "## Caveats",
        "",
        "- This benchmark is small (~50 items across 10 categories) -- these numbers "
        "demonstrate the probing methodology, not a validated classifier.",
        "- No cross-validation was run; a single train/test split was used.",
    ]
    _DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    _DOCS_PATH.write_text("\n".join(lines) + "\n")


def main() -> None:
    X, y, ids = _build_dataset()

    label_counts: dict[str, int] = {}
    for label in y:
        label_counts[label] = label_counts.get(label, 0) + 1
    stratify = y if min(label_counts.values()) >= 2 else None

    X_train, X_test, y_train, y_test, _id_train, id_test = train_test_split(
        X, y, ids, test_size=0.25, random_state=42, stratify=stratify
    )

    candidates = {
        "logistic_regression": make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000)),
        "random_forest": RandomForestClassifier(n_estimators=200, random_state=42),
        "mlp": make_pipeline(StandardScaler(), MLPClassifier(hidden_layer_sizes=(16,), max_iter=3000, random_state=42)),
    }

    results = {}
    for name, clf in candidates.items():
        clf.fit(X_train, y_train)
        preds = clf.predict(X_test)
        acc = accuracy_score(y_test, preds)
        results[name] = {"model": clf, "accuracy": acc, "preds": preds}
        print(f"{name}: test accuracy = {acc:.3f}")

    best_name = max(results, key=lambda n: results[n]["accuracy"])
    best = results[best_name]

    _SAVED_DIR.mkdir(parents=True, exist_ok=True)
    import joblib

    joblib.dump(best["model"], _SAVED_DIR / "probe_pipeline.joblib")

    categories = sorted(set(y))
    meta = {
        "probe_type": best_name,
        "test_accuracy": best["accuracy"],
        "n_train": len(X_train),
        "n_test": len(X_test),
        "categories": categories,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "feature_names": FEATURE_NAMES,
        "all_results": {k: v["accuracy"] for k, v in results.items()},
    }
    (_SAVED_DIR / "probe_meta.json").write_text(json.dumps(meta, indent=2))

    cm = confusion_matrix(y_test, best["preds"], labels=categories)
    _write_report(results, best_name, categories, cm, len(id_test))
    print(f"\nBest probe: {best_name} ({best['accuracy']:.3f} test accuracy). Saved to {_SAVED_DIR}.")


if __name__ == "__main__":
    main()
